package model

type DishSpecification struct {
	Name                      string
	Diameter                  string
	Type                      string
	BuiltIn                   string
	TransmittersFrequency     string
	ReceiversFrequency        string
	TransmittersPower         string
	Precision                 string
	TotalWeight               string
	DishWeight                string
	AntennaSpeed              string
	TotalPanels               string
	SurfaceArea               string
	OperationalWindResistance string
	WindResistance            string
	WebUrl                    string
	Location                  string
}

func (d *Dish) GetDishSpecification() DishSpecification {
	if spec, ok := dishSpecs[d.Name]; ok {
		return spec
	}

	return DishSpecification{}
}

var dishSpecs = map[string]DishSpecification{
	// gdscc
	"DSS14": {
		Name:                      "DSS-14",
		Diameter:                  "70 meters",
		Type:                      "",
		BuiltIn:                   "",
		TransmittersFrequency:     "",
		ReceiversFrequency:        "",
		TransmittersPower:         "",
		Precision:                 "",
		TotalWeight:               "",
		DishWeight:                "",
		AntennaSpeed:              "",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "",
		WindResistance:            "",
		WebUrl:                    "",
		Location:                  "gdscc",
	},
	"DSS24": {
		Name:                      "DSS-24",
		Diameter:                  "",
		Type:                      "",
		BuiltIn:                   "",
		TransmittersFrequency:     "",
		ReceiversFrequency:        "",
		TransmittersPower:         "",
		Precision:                 "",
		TotalWeight:               "",
		DishWeight:                "",
		AntennaSpeed:              "",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "",
		WindResistance:            "",
		WebUrl:                    "",
		Location:                  "gdscc",
	},
	"DSS25": {
		Name:                      "DSS-25",
		Diameter:                  "",
		Type:                      "",
		BuiltIn:                   "",
		TransmittersFrequency:     "",
		ReceiversFrequency:        "",
		TransmittersPower:         "",
		Precision:                 "",
		TotalWeight:               "",
		DishWeight:                "",
		AntennaSpeed:              "",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "",
		WindResistance:            "",
		WebUrl:                    "",
		Location:                  "gdscc",
	},
	"DSS26": {
		Name:                      "DSS-26",
		Diameter:                  "",
		Type:                      "",
		BuiltIn:                   "",
		TransmittersFrequency:     "",
		ReceiversFrequency:        "",
		TransmittersPower:         "",
		Precision:                 "",
		TotalWeight:               "",
		DishWeight:                "",
		AntennaSpeed:              "",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "",
		WindResistance:            "",
		WebUrl:                    "",
		Location:                  "gdscc",
	},
	// cdscc
	"DSS34": {
		Name:                      "DSS-34",
		Diameter:                  "34 meters",
		Type:                      "Azimuth-Elevation Beam Wave Guide",
		BuiltIn:                   "1997",
		TransmittersFrequency:     "X and S bands",
		ReceiversFrequency:        "X, S, K, Ka and X bands",
		TransmittersPower:         "",
		Precision:                 "0.004 degrees",
		TotalWeight:               "",
		DishWeight:                "",
		AntennaSpeed:              "0.8 degrees/s",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "72 km/h",
		WindResistance:            "160 km/h",
		WebUrl:                    "https://www.cdscc.nasa.gov/Pages/Antennas/dss34.html",
		Location:                  "cdscc",
	},
	"DSS35": {
		Name:                      "DSS-35",
		Diameter:                  "34 meters",
		Type:                      "Azimuth-Elevation Beam Wave Guide",
		BuiltIn:                   "2014",
		TransmittersFrequency:     "X band",
		ReceiversFrequency:        "X and Ka bands",
		TransmittersPower:         "",
		Precision:                 "0.004 degrees",
		TotalWeight:               "",
		DishWeight:                "",
		AntennaSpeed:              "0.8 degrees/s",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "72 km/h",
		WindResistance:            "160 km/h",
		WebUrl:                    "https://www.cdscc.nasa.gov/Pages/Antennas/dss35.html",
		Location:                  "cdscc",
	},
	"DSS36": {
		Name:                      "DSS-36",
		Diameter:                  "34 meters",
		Type:                      "Azimuth-Elevation Beam Wave Guide",
		BuiltIn:                   "2016",
		TransmittersFrequency:     "X and S bands",
		ReceiversFrequency:        "X, S and Ka bands",
		TransmittersPower:         "",
		Precision:                 "0.004 degrees",
		TotalWeight:               "",
		DishWeight:                "",
		AntennaSpeed:              "0.8 degrees/s",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "72 km/h",
		WindResistance:            "160 km/h",
		WebUrl:                    "https://www.cdscc.nasa.gov/Pages/Antennas/dss36.html",
		Location:                  "cdscc",
	},
	"DSS43": {
		Name:                      "DSS-43",
		Diameter:                  "70 meters",
		Type:                      "Azimuth-Elevation",
		BuiltIn:                   "1972",
		TransmittersFrequency:     "X and S bands",
		ReceiversFrequency:        "X, S, L and K bands",
		TransmittersPower:         "",
		Precision:                 "0.005 degrees",
		TotalWeight:               "3000 tons",
		DishWeight:                "",
		AntennaSpeed:              "0.25 degrees/s",
		TotalPanels:               "1272",
		SurfaceArea:               "4180 m²",
		OperationalWindResistance: "72 km/h",
		WindResistance:            "160 km/h",
		WebUrl:                    "https://www.cdscc.nasa.gov/Pages/Antennas/dss43.html",
		Location:                  "cdscc",
	},
	// mdscc
	"DSS53": {
		Name:                      "DSS-53",
		Diameter:                  "34 meters",
		Type:                      "Azimuth-Elevation",
		BuiltIn:                   "2022",
		TransmittersFrequency:     "X band",
		ReceiversFrequency:        "X and Ka bands",
		TransmittersPower:         "20 Kw",
		Precision:                 "0.010 degrees",
		TotalWeight:               "400 tons",
		DishWeight:                "",
		AntennaSpeed:              "0.8 degrees/s",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "80 km/h",
		WindResistance:            "160 km/h",
		WebUrl:                    "https://www.mdscc.nasa.gov/index.php/en/dss-53/",
		Location:                  "mdscc",
	},
	"DSS54": {
		Name:                      "DSS-54",
		Diameter:                  "34 meters",
		Type:                      "Azimuth-Elevation",
		BuiltIn:                   "1997",
		TransmittersFrequency:     "S and X bands",
		ReceiversFrequency:        "S, X and K bands",
		TransmittersPower:         "20 Kw",
		Precision:                 "0.010 degrees",
		TotalWeight:               "358 tons",
		DishWeight:                "",
		AntennaSpeed:              "0.8 degrees/s",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "64 km/h",
		WindResistance:            "160 km/h",
		WebUrl:                    "https://www.mdscc.nasa.gov/index.php/en/dss-54-2/",
		Location:                  "mdscc",
	},
	"DSS55": {
		Name:                      "DSS-55",
		Diameter:                  "34 meters",
		Type:                      "Azimuth-Elevation",
		BuiltIn:                   "2003",
		TransmittersFrequency:     "S and X bands",
		ReceiversFrequency:        "S, X and K bands",
		TransmittersPower:         "20 Kw",
		Precision:                 "0.010 degrees",
		TotalWeight:               "358 tons",
		DishWeight:                "",
		AntennaSpeed:              "0.8 degrees/s",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "64 km/h",
		WindResistance:            "160 km/h",
		WebUrl:                    "https://www.mdscc.nasa.gov/index.php/en/dss-55-2/",
		Location:                  "mdscc",
	},
	"DSS56": {
		Name:                      "DSS-56",
		Diameter:                  "34 meters",
		Type:                      "Azimuth-Elevation",
		BuiltIn:                   "2021",
		TransmittersFrequency:     "S and X bands",
		ReceiversFrequency:        "S, X, Ka and K II bands",
		TransmittersPower:         "20 Kw",
		Precision:                 "0.010 degrees",
		TotalWeight:               "400 tons",
		DishWeight:                "",
		AntennaSpeed:              "0.8 degrees/s",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "80 km/h",
		WindResistance:            "160 km/h",
		WebUrl:                    "https://www.mdscc.nasa.gov/index.php/en/dss-56-2/",
		Location:                  "mdscc",
	},
	"DSS63": {
		Name:                      "DSS-63",
		Diameter:                  "70 meters",
		Type:                      "Azimuth-Elevation",
		BuiltIn:                   "1974",
		TransmittersFrequency:     "S and X bands",
		ReceiversFrequency:        "L, S, X and K bands",
		TransmittersPower:         "20 Kw",
		Precision:                 "0.005 degrees",
		TotalWeight:               "8000 tons",
		DishWeight:                "3500 tons",
		AntennaSpeed:              "0.25 degrees/s",
		TotalPanels:               "1272",
		SurfaceArea:               "4180 m²",
		OperationalWindResistance: "64 km/h",
		WindResistance:            "160 km/h",
		WebUrl:                    "https://www.mdscc.nasa.gov/index.php/en/dss-63-2/",
		Location:                  "mdscc",
	},
	"DSS65": {
		Name:                      "DSS-65",
		Diameter:                  "34 meters",
		Type:                      "Azimuth-Elevation",
		BuiltIn:                   "1987",
		TransmittersFrequency:     "S and X bands",
		ReceiversFrequency:        "S and X bands",
		TransmittersPower:         "20 Kw",
		Precision:                 "0.010 degrees",
		TotalWeight:               "400 tons",
		DishWeight:                "3500 tons",
		AntennaSpeed:              "0.8 degrees/s",
		TotalPanels:               "",
		SurfaceArea:               "",
		OperationalWindResistance: "64 km/h",
		WindResistance:            "160 km/h",
		WebUrl:                    "https://www.mdscc.nasa.gov/index.php/en/dss-65-2/",
		Location:                  "mdscc",
	},
}
